(function(){
var g=false,h=null,m=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_tag_js_version:"gut",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",
google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",
google_rt:"rt",google_skip:"skip"},da={google_only_pyv_ads:"pyv"};function ea(a){return ba[a]||ca[a]||da[a]||h};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function n(){this.I=this.xb();this.Ta=g;if(!this.I)this.Ta=this.ab()}n.prototype.ia="__gads=";n.prototype.S="GoogleAdServingTest=";n.prototype.hb=function(){return this.I};n.prototype.setCookieInfo=function(a){this.B=a._cookies_[0];if(this.B!=h){this.I=this.B._value_;this.Gb()}};n.prototype.db=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
n.prototype.cb=function(a){if(!(this.I!=h||!this.Ta)){var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+fa(a)+"&domain="+fa(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};n.prototype.ab=function(){document.cookie=this.S+"Good";var a=this.Fa(this.S),b=a=="Good";if(b){var c=this.db(-1);document.cookie=this.S+"; expires="+c.toGMTString()}return b};n.prototype.xb=function(){var a=this.Fa(this.ia);return a};
n.prototype.Fa=function(a){var b=document.cookie,c=b.indexOf(a),d=h;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};n.prototype.Gb=function(){if(!(this.B==h))if(!(this.I==h)){var a=new Date;a.setTime(1000*this.B._expires_);var b=this.B._domain_,c=this.ia+this.I+"; expires="+a.toGMTString()+"; path="+this.B._path_+"; domain=."+b;document.cookie=c}};function ga(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function ha(a,b){if(a=="true")return m;if(a=="false")return g;return b}
function ia(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;for(;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b.toString()}else if(ja()){var c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=h){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var ka=ka||{},r=this,ma=function(a,b,c){var d=a.split("."),e=c||r,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(;d.length&&(f=d.shift());)if(!d.length&&la(b))e[f]=b;else if(e[f])e=e[f];else{e[f]={};e=e[f]}},na=function(a,b){var c=a.split("."),d=b||r,e;for(;e=c.shift();)if(d[e])d=d[e];else return h;return d},s=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!pa(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b},qa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return m;return g};if(Object.prototype.propertyIsEnumerable)var pa=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):qa(a,b)};else pa=qa;var la=function(a){return typeof a!="undefined"};
var ra=function(a){return s(a)=="function"},sa=function(a){var b=s(a);return b=="object"||b=="array"||b=="function"},va=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ta)){var b=a[ta];if(b)return b}a[ta]||(a[ta]=++ua);return a[ta]},ta="closure_hashCode_",ua=0,wa=function(a){var b=s(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=wa(a[d]);return c}return a},t=function(a,b){var c=a.Hb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,
2);c&&d.unshift.apply(d,c);c=d}b=a.Jb||b;a=a.Ib||a;var e,f=b||r;e=c?function(){var j=Array.prototype.slice.call(arguments);j.unshift.apply(j,c);return a.apply(f,j)}:function(){return a.apply(f,arguments)};e.Hb=c;e.Jb=b;e.Ib=a;return e},xa=Date.now||function(){return(new Date).getTime()},ya=function(a,b,c){ma(a,b,c)},u=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a};var za=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==h?0:c<0?Math.max(0,a.length+c):c,e=d;for(;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},Aa=function(a,b){var c=za(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};var Ba=function(a,b){this.x=la(a)?a:0;this.y=la(b)?b:0};Ba.prototype.clone=function(){return new Ba(this.x,this.y)};Ba.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var v=function(a,b){this.width=a;this.height=b};v.prototype.clone=function(){return new v(this.width,this.height)};v.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};v.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};v.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
v.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};v.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ca=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Da=function(a,b){var c=b.length,d=0;for(;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var Fa=function(a,b){var c=0,d=Ca(String(a)).split("."),e=Ca(String(b)).split("."),f=Math.max(d.length,e.length),j=0;for(;c==0&&j<f;j++){var i=d[j]||"",l=e[j]||"",k=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var p=k.exec(i)||["","",""],q=o.exec(l)||["","",""];if(p[0].length==0&&q[0].length==0)break;var K=p[1].length==0?0:parseInt(p[1],10),N=q[1].length==0?0:parseInt(q[1],10);c=Ea(K,N)||Ea(p[2].length==0,q[2].length==0)||Ea(p[2],q[2])}while(c==0)}return c},Ea=function(a,b){if(a<
b)return-1;else if(a>b)return 1;return 0};var Ga,Ha,Ia,Ja,Ka,La,Ma,Na,Oa,Pa=function(){return r.navigator?r.navigator.userAgent:h};var Qa=function(){La=Ka=Ja=Ia=Ha=Ga=g;var a;if(a=Pa()){var b=r.navigator;Ga=a.indexOf("Opera")==0;Ha=!Ga&&a.indexOf("MSIE")!=-1;Ja=(Ia=!Ga&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;La=(Ka=!Ga&&!Ia&&b.product=="Gecko")&&b.vendor=="Camino"}};Qa();
var Ra=Ga,w=Ha,Sa=Ka,Ta=La,x=Ia,Ua=Ja,Va=function(){var a=r.navigator;return a&&a.platform||""},Wa=Va(),Xa=function(){Ma=Wa.indexOf("Mac")!=-1;Na=Wa.indexOf("Win")!=-1;Oa=Wa.indexOf("Linux")!=-1};Xa();var Ya=Ma,Za=Na,$a=Oa,ab=function(){var a="",b;if(Ra&&r.opera){var c=r.opera.version;a=typeof c=="function"?c():c}else{if(Sa)b=/rv\:([^\);]+)(\)|;)/;else if(w)b=/MSIE\s+([^\);]+)(\)|;)/;else if(x)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Pa());a=d?d[1]:""}}return a},bb=ab();
var y=function(a){return Fa(bb,a)>=0};var cb;var ib=function(a){return a?new z(hb(a)):cb||(cb=new z)};var jb=function(a){return typeof a=="string"?document.getElementById(a):a},kb=jb,lb=function(a){var b=a||r||window,c=b.document;if(x&&!y("500")&&!Ua){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new v(b.innerWidth,d)}var f=ib(c),j=f.Z()&&(!Ra||Ra&&y("9.50"))?c.documentElement:c.body;return new v(j.clientWidth,j.clientHeight)};
var mb=function(a,b){a.appendChild(b)},nb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):h},ob=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)},pb=x&&Fa(bb,"521")<=0,qb=function(a,b){if(typeof a.contains!="undefined"&&!pb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},hb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},z=
function(a){this.C=a||r.document||document};z.prototype.wa=function(){return this.C};z.prototype.ya=function(a){return typeof a=="string"?this.C.getElementById(a):a};z.prototype.createElement=function(a){return this.C.createElement(a)};z.prototype.createTextNode=function(a){return this.C.createTextNode(a)};
z.prototype.Z=function(){var a=this.C;if(a.compatMode)return a.compatMode=="CSS1Compat";if(x){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return g};z.prototype.fb=function(){var a=this.C;return!x&&this.Z()?a.documentElement:a.body};z.prototype.xa=function(){var a=this.fb();return new Ba(a.scrollLeft,a.scrollTop)};z.prototype.appendChild=mb;
z.prototype.removeNode=nb;z.prototype.replaceNode=ob;z.prototype.contains=qb;var rb,sb=function(a,b){var c=hb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return h};var tb=function(a,b){return sb(a,b)||(a.currentStyle?a.currentStyle[b]:h)||a.style[b]};
var ub=function(a){var b;b=a?a.nodeType==9?a:hb(a):document;if(w&&!ib(b).Z())return b.body;return b.documentElement},vb=function(a){var b=a.getBoundingClientRect();if(w){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},wb=function(a){if(w)return a.offsetParent;var b=hb(a),c=tb(a,"position"),d=c=="fixed"||c=="absolute",e=a.parentNode;for(;e&&e!=b;e=e.parentNode){c=tb(e,"position");d=d&&c=="static"&&e!=b.documentElement;
if(!d&&(e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight||c=="fixed"||c=="absolute"))return e}return h},xb=function(a){var b,c=hb(a),d=tb(a,"position"),e=Sa&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0);if(typeof rb=="undefined")rb=Ta&&!y("1.8.0.11");var f=new Ba(0,0),j=ub(c);if(a==j)return f;if(a.getBoundingClientRect){b=vb(a);var i=ib(c).xa();f.x=b.left+i.x;f.y=b.top+i.y}else if(c.getBoxObjectFor&&!e&&!rb){b=c.getBoxObjectFor(a);
var l=c.getBoxObjectFor(j);f.x=b.screenX-l.screenX;f.y=b.screenY-l.screenY}else{var k=a;do{f.x+=k.offsetLeft;f.y+=k.offsetTop;if(k!=a){f.x+=k.clientLeft||0;f.y+=k.clientTop||0}if(x&&tb(k,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}k=k.offsetParent}while(k&&k!=a);if(Ra||x&&d=="absolute")f.y-=c.body.offsetTop;k=a;for(;k=wb(k);){f.x-=k.scrollLeft;if(!Ra||k.tagName!="TR")f.y-=k.scrollTop}}return f},yb=function(a){var b=new Ba;if(a.nodeType==1)if(a.getBoundingClientRect){var c=
vb(a);b.x=c.left;b.y=c.top}else{var d=ib(a).xa(),e=xb(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},zb=function(a){var b=hb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=tb(a,"fontFamily");if(Ra&&$a)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Da(c,"\"'")};var Ab=document,A=navigator,B=window;
function Bb(){var a=Ab.cookie,b=Math.round((new Date).getTime()/1000),c=B.google_analytics_domain_name,d=typeof c=="undefined"?Cb("auto"):Cb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,j=a.indexOf("__utmc="+d)>-1,i,l={};if(e){i=a.split("__utma="+d+".")[1].split(";")[0].split(".");l.sid=f&&j?i[3]+"":B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";l.vid=i[0]+"."+i[1];l.from_cookie=m}else{l.sid=B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";l.vid=B&&B.gaGlobal&&B.gaGlobal.vid?
B.gaGlobal.vid:(Db()^Eb()&2147483647)+"."+b;l.from_cookie=g}l.dh=d;l.hid=B&&B.gaGlobal&&B.gaGlobal.hid?B.gaGlobal.hid:Db();return B.gaGlobal=l}function Db(){return Math.round(Math.random()*2147483647)}
function Eb(){var a=Ab.cookie?Ab.cookie:"",b=B.history.length,c,d,e=[A.appName,A.version,A.language?A.language:A.browserLanguage,A.platform,A.userAgent,A.javaEnabled()?1:0].join("");if(B.screen)e+=B.screen.width+"x"+B.screen.height+B.screen.colorDepth;else if(B.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=Ab.referrer?Ab.referrer:"";c=e.length;for(;b>0;)e+=b--^c++;return Fb(e)}
function Fb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;d=a.length-1;for(;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Cb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Ab.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Fb(a.toLowerCase())};var C=function(){};C.prototype.va=g;C.prototype.dispose=function(){if(!this.va){this.va=m;this.b()}};C.prototype.b=function(){};var Gb=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Hb=function(a){String(a);if(Gb(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var D=function(){};D.prototype.serialize=function(a){var b=[];this.ga(a,b);return b.join("")};
D.prototype.ga=function(a,b){switch(typeof a){case "string":this.Ia(a,b);break;case "number":this.Db(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==h){b.push("null");break}if(s(a)=="array"){this.Cb(a,b);break}this.Eb(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Ib={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Jb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x80-\uffff]/g:/[\\\"\x00-\x1f\x80-\xff]/g;D.prototype.Ia=function(a,b){b.push('"',a.replace(Jb,function(c){if(c in Ib)return Ib[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Ib[c]=e+d.toString(16)}),'"')};D.prototype.Db=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
D.prototype.Cb=function(a,b){var c=a.length;b.push("[");var d="",e=0;for(;e<c;e++){b.push(d);this.ga(a[e],b);d=","}b.push("]")};D.prototype.Eb=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Ia(d,b);b.push(":");this.ga(e,b);c=","}}b.push("}")};var E="SETUP_ACK",F={},Lb=function(a,b){var c=b||Kb,d=c.length,e="";for(;a-- >0;)e+=c.charAt(Math.floor(Math.random()*d));return e},Kb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var G=function(){};u(G,C);G.prototype.f=0;var H=function(a){this.a=a;this.Q=[];this.Ob=t(this.Za,this)};u(H,G);H.prototype.f=2;H.prototype.ca=g;H.prototype.Fb=0;H.prototype.connect=function(){if(this.a.s()==0){this.l=this.a.t;this.l.XPC_toOuter=t(this.za,this)}else this.ma()};
H.prototype.ma=function(){var a=m;try{if(!this.l)this.l=window.frameElement;if(this.l&&this.l.XPC_toOuter){this.Da=this.l.XPC_toOuter;this.l.XPC_toOuter.XPC_toInner=t(this.za,this);a=g;this.send("tp",E);this.a.m()}}catch(b){}if(a){if(!this.Ma)this.Ma=t(this.ma,this);window.setTimeout(this.Ma,100)}};H.prototype.H=function(a){if(this.a.s()==0&&!this.a.g()&&a==E){this.Da=this.l.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};
H.prototype.za=function(a,b){if(!this.ca&&this.Q.length==0)this.a.j(a,b);else{this.Q.push({serviceName:a,payload:b});if(this.Q.length==1)this.Fb=window.setTimeout(this.Ob,1)}};H.prototype.Za=function(){for(;this.Q.length;){var a=this.Q.shift();this.a.j(a.serviceName,a.payload)}};H.prototype.send=function(a,b){this.ca=m;this.Da(a,b);this.ca=g};H.prototype.b=function(){H.o.b.call(this);this.l=this.Da=h};var I=function(a){this.a=a;this.R=this.a.c.ppu;this.Qb=this.a.c.lpu;this.ea=[]},Mb,Nb;u(I,G);I.prototype.f=4;I.prototype.fa=0;I.prototype.w=g;I.prototype.O=g;var Ob="googlexpc";I.prototype.M=function(){return Ob+"_"+this.a.name+"_msg"};I.prototype.L=function(){return Ob+"_"+this.a.name+"_ack"};I.prototype.connect=function(){if(!this.O){this.Sa();this.O=m}this.Oa()};I.prototype.Sa=function(){var a=this.M();this.D=this.W(a);this.Ba=window.frames[a];a=this.L();this.p=this.W(a);this.U=window.frames[a]};
I.prototype.W=function(a){var b=document.createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.name=a;b.id=b.name;b.src=this.R+"#INITIAL";document.body.appendChild(b);return b};I.prototype.nb=function(){this.a.name=Lb(10);this.sa();this.O=g;this.Sb=this.W(Ob+"_reconnect_"+this.a.name)};
I.prototype.sb=function(){var a=this.a.h.frames,b=a.length,c=0;for(;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!!d){var f=d.split("_");if(f.length==3&&f[0]==Ob&&f[1]=="reconnect"){this.a.name=f[2];this.sa();this.O=g;break}}}};I.prototype.sa=function(){if(this.D){this.D.parentNode.removeChild(this.D);this.Ba=this.D=h}if(this.p){this.p.parentNode.removeChild(this.p);this.U=this.p=h}};
I.prototype.Oa=function(){if(this.Aa(this.M())&&this.Aa(this.L())){this.pb=new Pb(this,this.a.h.frames[this.M()],t(this.vb,this));this.ja=new Pb(this,this.a.h.frames[this.L()],t(this.ub,this));this.pa()}else{if(this.a.s()==1&&!this.Sb)this.nb();else this.a.s()==0&&this.sb();window.setTimeout(t(this.connect,this),100)}};I.prototype.Aa=function(a){try{var b=this.a.h.frames[a];if(!b||b.location.href.indexOf(this.Qb)!=0)return g}catch(c){return g}return m};
I.prototype.pa=function(){var a=this.a.h.frames;if(a[this.L()]&&a[this.M()]){this.qb=new Qb(this.R,this.Ba);this.T=new Qb(this.R,this.U);window.setTimeout(t(function(){this.qb.send("SETUP");this.w=this.Vb=m},this),100)}else{if(!this.Pa)this.Pa=t(this.pa,this);window.setTimeout(this.Pa,100)}};I.prototype.oa=function(){if(this.Bb&&this.Rb){this.a.m();if(this.K){var a=0,b;for(;a<this.K.length;a++){b=this.K[a];this.a.j(b.service,b.payload)}delete this.K}}};
I.prototype.vb=function(a){if(a=="SETUP"){if(!!this.T){this.T.send(E);this.Bb=m;this.oa()}}else if(this.a.g()||this.Bb){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.T.send("ACK:"+e);this.ta(d)}else{var e=c.substring(0,b);this.T.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Ea=[];this.Ea.push(d);if(f[0]==f[1]){this.ta(this.Ea.join(""));delete this.Ea}}}};
I.prototype.ub=function(a){if(a==E){this.w=g;this.Rb=m;this.oa()}else if(this.a.g())if(!!this.w){var b=parseInt(a.split(":")[1],10);if(b==this.fa){this.w=g;this.Ha()}}};I.prototype.Ha=function(){if(!(this.w||!this.ea.length)){var a=this.ea.shift();++this.fa;this.qb.send(this.fa+a);this.w=m}};I.prototype.ta=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.g()?this.a.j(c,d):(this.K||(this.K=[])).push({service:c,payload:d})};I.prototype.J=3800;
I.prototype.send=function(a,b){var c=a+":"+b;if(!w||b.length<=this.J)this.ea.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.J),f=0,j=1;for(;f<d;){this.ea.push(","+j+"/"+e+"|"+c.substr(f,this.J));j++;f+=this.J}}this.Ha()};I.prototype.b=function(){I.o.b.call(this);var a=Rb;Aa(a,this.pb);Aa(a,this.ja);this.pb=this.ja=h;nb(this.D);nb(this.p);this.Ba=this.U=this.D=this.p=h};
var Rb=[],Tb=function(){var a=g;try{var b=0,c=Rb.length;for(;b<c;b++)a=a||Rb[b].receive()}catch(d){Rb[b].d.a.rb();if(!Rb.length)return}var e=xa();if(a)Mb=e;var f=e-Mb<1000?10:100;Nb=window.setTimeout(Sb,f)},Sb=t(Tb,I),Ub=function(){Mb=xa();Nb&&window.clearTimeout(Nb);Nb=window.setTimeout(Sb,10)},Qb=function(a,b){this.R=a;this.Ab=b;this.ra=0};Qb.prototype.send=function(a){this.ra=++this.ra%2;var b=this.R+"#"+this.ra+encodeURIComponent(a);try{if(x)this.Ab.location.href=b;else this.Ab.location.replace(b)}catch(c){}Ub()};
var Pb=function(a,b,c){this.d=a;this.wb=b;this.Kb=c;this.Xa=this.wb.location.href.split("#")[0]+"#INITIAL";Rb.push(this);Ub()};Pb.prototype.receive=function(){var a=this.wb.location.href;if(a!=this.Xa){this.Xa=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Kb(decodeURIComponent(b))}return m}else return g};var J=function(a,b){C.call(this);this.ob=b;this.r=[];this.Va(a)};u(J,C);J.prototype.X=h;J.prototype.Y=h;J.prototype.G=function(a){this.X=a};J.prototype.Ka=function(a){this.Y=a};J.prototype.k=function(){if(this.r.length)return this.r.pop();return this.qa()};J.prototype.v=function(a){this.r.length<this.ob?this.r.push(a):this.ua(a)};J.prototype.Va=function(a){if(a>this.ob)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");var b=0;for(;b<a;b++)this.r.push(this.qa())};
J.prototype.qa=function(){return this.X?this.X():{}};J.prototype.ua=function(a){if(this.Y)this.Y(a);else if(ra(a.dispose))a.dispose();else for(var b in a)delete a[b]};J.prototype.b=function(){J.o.b.call(this);var a=this.r;for(;a.length;)this.ua(a.pop());delete this.r};var L=function(a,b){this.type=a;this.currentTarget=this.target=b};u(L,C);L.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.F=g;L.prototype.da=m;L.prototype.stopPropagation=function(){this.F=m};L.prototype.preventDefault=function(){this.da=g};var M=function(a,b){a&&this.init(a,b)};u(M,L);M.prototype.type=h;M.prototype.target=h;M.prototype.relatedTarget=h;M.prototype.offsetX=0;M.prototype.offsetY=0;M.prototype.clientX=0;M.prototype.clientY=0;M.prototype.screenX=0;M.prototype.screenY=0;M.prototype.button=0;M.prototype.keyCode=0;M.prototype.charCode=0;M.prototype.ctrlKey=g;M.prototype.altKey=g;M.prototype.shiftKey=g;M.prototype.metaKey=g;M.prototype.i=h;
M.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:h;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.i=a;delete this.da;delete this.F};M.prototype.stopPropagation=function(){this.F=m;if(this.i.stopPropagation)this.i.stopPropagation();else this.i.cancelBubble=m};
M.prototype.preventDefault=function(){this.da=g;if(this.i.preventDefault)this.i.preventDefault();else{this.i.returnValue=g;try{this.i.keyCode=-1}catch(a){}}};M.prototype.eb=function(){return this.i};M.prototype.b=function(){M.o.b.call(this);this.i=h};var O=function(){},Vb=0;O.prototype.aa=h;O.prototype.listener=h;O.prototype.proxy=h;O.prototype.src=h;O.prototype.type=h;O.prototype.capture=h;O.prototype.handler=h;O.prototype.key=0;O.prototype.removed=g;O.prototype.na=g;
O.prototype.init=function(a,b,c,d,e,f){if(ra(a))this.aa=m;else if(a&&a.handleEvent&&ra(a.handleEvent))this.aa=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.na=g;this.key=++Vb;this.removed=g};O.prototype.handleEvent=function(a){if(this.aa)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var Wb={},P={},Xb={},Yb=new J(0,600);Yb.G(function(){return{q:0}});Yb.Ka(function(a){a.q=0});var Q=new J(0,600);Q.G(function(){return[]});Q.Ka(function(a){a.length=0;delete a.P;delete a.Ca});var Zb=new J(0,600);Zb.G(function(){var a=function(b){return bc.call(a.src,a.key,b)};return a});var cc=function(){return new O},dc=new J(0,600);dc.G(cc);
var ec=function(){return new M},fc=function(){var a=h;if(w){a=new J(0,600);a.G(ec)}return a},gc=fc(),hc="on",ic={},jc=function(a,b,c,d,e){if(b)if(s(b)=="array"){var f=0;for(;f<b.length;f++)jc(a,b[f],c,d,e);return h}else{var j=!!d,i=P;b in i||(i[b]=Yb.k());i=i[b];if(!(j in i)){i[j]=Yb.k();i.q++}i=i[j];var l=va(a),k,o;if(i[l]){k=i[l];var f=0;for(;f<k.length;f++){o=k[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return k[f].key}}}else{i[l]=Q.k();k=i[l];i.q++}var p=Zb.k();p.src=a;o=dc.k();o.init(c,
p,a,b,j,e);var q=o.key;p.key=q;k.push(o);Wb[q]=o;Xb[l]||(Xb[l]=Q.k());Xb[l].push(o);if(a.addEventListener){if(a==r||!a.Nb)a.addEventListener(b,p,j)}else a.attachEvent(kc(b),p);return q}else throw Error("Invalid event type");},lc=function(a,b,c,d,e){if(s(b)=="array"){var f=0;for(;f<b.length;f++)lc(a,b[f],c,d,e);return h}var j=!!d,i=mc(a,b,j);if(!i)return g;var f=0;for(;f<i.length;f++)if(i[f].listener==c&&i[f].capture==j&&i[f].handler==e)return nc(i[f].key);return g},nc=function(a){if(!Wb[a])return g;
var b=Wb[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==r||!c.Nb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(kc(d),e);var j=va(c),i=P[d][f][j];if(Xb[j]){var l=Xb[j];Aa(l,b);l.length==0&&delete Xb[j]}b.removed=m;i.Ca=m;oc(d,f,j,i);delete Wb[a];return m},oc=function(a,b,c,d){if(!d.P)if(d.Ca){var e=0,f=0;for(;e<d.length;e++)if(d[e].removed)dc.v(d[e]);else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Ca=g;if(f==0){Q.v(d);delete P[a][b][c];
P[a][b].q--;if(P[a][b].q==0){Yb.v(P[a][b]);delete P[a][b];P[a].q--}if(P[a].q==0){Yb.v(P[a]);delete P[a]}}}},mc=function(a,b,c){var d=P;if(b in d){d=d[b];if(c in d){d=d[c];var e=va(a);if(d[e])return d[e]}}return h},kc=function(a){if(a in ic)return ic[a];return ic[a]=hc+a},qc=function(a,b,c,d){var e=1,f=P;if(b in f){f=f[b];if(c in f){f=f[c];var j=va(a);if(f[j]){var i=f[j];if(i.P)i.P++;else i.P=1;try{var l=i.length,k=0;for(;k<l;k++){var o=i[k];if(o&&!o.removed)e&=pc(o,d)!==g}}finally{i.P--;oc(b,c,j,
i)}}}}return Boolean(e)},pc=function(a,b){var c=a.handleEvent(b);a.na&&nc(a.key);return c},bc=function(a,b){if(!Wb[a])return m;var c=Wb[a],d=c.type,e=P;if(!(d in e))return m;e=e[d];var f;if(w){var j=b||na("window.event"),i=m in e;if(i){if(j.keyCode<0||j.returnValue!=undefined)return m;rc(j)}va(c.src);var l=gc.k();l.init(j,this);f=m;try{if(i){var k=Q.k(),o=l.currentTarget;for(;o;o=o.parentNode)k.push(o);var p=k.length-1;for(;!l.F&&p>=0;p--){l.currentTarget=k[p];f&=qc(k[p],d,m,l)}var p=0;for(;!l.F&&
p<k.length;p++){l.currentTarget=k[p];f&=qc(k[p],d,g,l)}}else f=pc(c,l)}finally{if(k){k.length=0;Q.v(k)}l.dispose();gc.v(l)}return f}var q=new M(b,this);try{f=pc(c,q)}finally{q.dispose()}return f},rc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=m}if(b||a.returnValue==undefined)a.returnValue=m};var R=function(a){this.a=a;this.Pb=this.a.c.pru;this.tb=this.a.c.ifrid;x&&sc()};u(R,G);if(x)var tc=[],uc=0,sc=function(){uc||(uc=window.setTimeout(function(){vc()},1000))},vc=function(a){var b=xa(),c=a||3000;for(;tc.length&&b-tc[0].timestamp>=c;){var d=tc.shift().iframeElement;nb(d)}uc=window.setTimeout(wc,1000)},wc=function(){vc()};R.prototype.f=3;R.prototype.connect=function(){this.send("tp","SETUP")};R.prototype.H=function(a){if(a=="SETUP"){this.send("tp",E);this.a.m()}else a==E&&this.a.m()};
R.prototype.send=function(a,b){if(w){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=xc}else{var d=document.createElement("iframe");x?tc.push({timestamp:xa(),iframeElement:d}):jc(d,"load",xc)}var e=d.style;e.visibility="hidden";d.style.height="0px";e.width=d.style.height;e.position="absolute";var f=this.Pb;f+="#"+this.a.name;if(this.tb)f+=","+this.tb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var xc=function(){nb(this);this.xpcOnload=h};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);F[a].j(d,decodeURIComponent(e))};R.prototype.b=function(){R.o.b.call(this);x&&vc(0)};var S=function(a,b){this.a=a;this.ba=b||"*"};u(S,G);S.prototype.f=1;var yc=g,Ac=function(){if(!yc){jc(window.postMessage?window:document,"message",zc,g,S);yc=m}},zc=function(a){var b=a.eb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return g;var e=b.substring(0,c),f=b.substring(c+1,d),j=b.substring(d+1),i=F[e];if(i){i.j(f,j);return m}for(var l in F){var k=F[l];if(k.s()==1&&!k.g()&&f=="tp"&&j=="SETUP"){k.name=e;F[e]=k;F[l]=h;k.j(f,j);return m}}return g};
S.prototype.H=function(a){switch(a){case "SETUP":if(!this.Tb){this.Tb=m;this.send("tp",E)}break;case E:this.a.m();break}};S.prototype.connect=function(){Ac();this.V()};S.prototype.V=function(){if(!this.a.g()){this.send("tp","SETUP");window.setTimeout(t(this.V,this),100)}};S.prototype.send=function(a,b){var c=this.a.h;if(!!c){var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.ba)};this.send(a,b)}};
S.prototype.b=function(){S.o.b.call(this);lc(window.postMessage?window:document,"message",zc,g,S)};var T=function(a){this.a=a;this.Na=a.at||"";this.zb=a.rat||"";Bc();this[Cc]=this.N;this[Dc]=this.Ua};u(T,G);
var Ec="GCXPC____NIXVBS_wrapper",Fc="GCXPC____NIXVBS_get_wrapper",Cc="GCXPC____NIXJS_handle_message",Dc="GCXPC____NIXJS_create_channel",Gc="GCXPC____NIXVBS_container",Bc=function(){if(!window.nix_setup_complete){var a="Class "+Ec+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Cc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Dc+"(channel)\nEnd Sub\nPublic Sub "+Gc+"()\n End Sub\nEnd Class\n Function "+Fc+"(transport, auth)\nDim wrap\nSet wrap = New "+Ec+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Fc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=m}catch(b){}}};T.prototype.f=6;T.prototype.u=g;T.prototype.n=h;T.prototype.connect=function(){this.a.s()==0?this.la():this.ka()};
T.prototype.la=function(){if(!this.u){var a=this.a.t;try{a.contentWindow.opener=window[Fc](this,this.Na);this.u=m}catch(b){}this.u||window.setTimeout(t(this.la,this),100)}};T.prototype.ka=function(){if(!this.u){try{var a=window.opener;if(a&&Gc in a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.zb)return;this.n.CreateChannel(window[Fc](this,this.Na));this.u=m;this.a.m()}}catch(c){return}this.u||window.setTimeout(t(this.ka,this),100)}};
T.prototype.Ua=function(a){this.n=a;var b=this.n.GetAuthToken();b!=this.zb||this.a.m()};T.prototype.N=function(a,b){function c(){this.a.j(a,b)}window.setTimeout(t(c,this),1)};T.prototype.send=function(a,b){this.n.SendMessage(a,b)};T.prototype.b=function(){T.o.b.call(this);this.n=h};var U=function(a){C.call(this);this.c=a;this.name=this.c.cn||Lb(10);this.Ja={};F[this.name]=this;jc(window,"unload",Hc)};u(U,C);U.prototype.d=h;U.prototype.ha=1;U.prototype.g=function(){return this.ha==2};U.prototype.h=h;U.prototype.t=h;U.prototype.La=function(a){this.h=a};
U.prototype.Wa=function(){if(!this.d){if(!this.c.tp)if(ra(document.postMessage)||ra(window.postMessage)||w&&window.postMessage)this.c.tp=1;else if(Sa)this.c.tp=2;else if(w&&this.c.pru)this.c.tp=3;else if(w)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.d=new S(this,this.c.ph);break;case 6:this.d=new T(this);break;case 2:this.d=new H(this);break;case 3:this.d=new R(this);break;case 4:this.d=new I(this);break}if(!this.d)throw Error("CrossPageChannel: No suitable transport found!");
}};U.prototype.Ya=g;U.prototype.Ra=g;U.prototype.connect=function(a){this.Mb=a;if(this.Ya)this.Ra=m;else{if(this.c.ifrid)this.t=typeof this.c.ifrid=="string"?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.t){var b=this.t.contentWindow;b||(b=window.frames[this.c.ifrid]);this.La(b)}if(!this.h)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.La(window.parent);this.Wa();this.d.connect()}};
U.prototype.close=function(){if(!!this.g()){this.ha=3;this.d.dispose();this.d=h}};U.prototype.m=function(){if(!this.g()){this.ha=2;this.Mb()}};U.prototype.rb=function(){this.close()};U.prototype.yb=function(a,b,c){this.Ja[a]={name:a,callback:b,jsonEncoded:!!c}};U.prototype.send=function(a,b){if(!!this.g())if(this.h.closed)this.close();else{if(sa(b))b=(new D).serialize(b);this.d.send(a,b)}};
U.prototype.j=function(a,b){if(!a||a=="tp")this.d.H(b);else if(this.g()){var c=this.Ja[a];if(c){if(c.jsonEncoded)try{b=Hb(b)}catch(d){return}c.callback(b)}}};U.prototype.s=function(){return window.parent==this.h?1:0};U.prototype.b=function(){U.o.b.call(this);this.close();this.t=this.h=h;delete this.Ja;F[this.name]=h};var Hc=function(){for(var a in F){var b=F[a];b&&b.dispose()}};var Ic=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var V=function(a,b){this.A=a.width;this.z=a.height;this.Lb=b;this.ba=this.gb(a.src,document);this.$=g;this.e=a;this.mb(this.ib())};V.prototype.ib=function(){var a={};a.ifrid=this.e.id;a.pu=this.e.src;a.ph=this.ba;a.cn=this.Lb;a.ppu=Ic(this.ba);a.lpu=Ic();return a};V.prototype.mb=function(a){this.a=new U(a);this.a.yb("expandable_ad",t(this.N,this));this.a.connect(function(){});window.setTimeout(t(this.kb,this),30000)};
V.prototype.kb=function(){if(this.a&&!this.a.g()){this.a.d.connect=function(){};if(this.a.d.f==1)this.a.d.V=function(){};if(this.a.d.f==4)this.a.d.Ub=function(){};this.a.d.dispose();this.a.dispose()}};V.prototype.gb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,j=f.indexOf("/");if(j<0)j=f.indexOf("?");if(d&&j>0)f=f.substring(0,j);return e+"//"+f};
V.prototype.N=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.lb(b);else c=="collapse"&&this.jb()};V.prototype.Ga=function(a){this.a.send("expandable_ad",a)};V.prototype.lb=function(a){if(!this.$){var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.$a(b,c);this.bb(b,c,f);this.Ga("ok_expand_w"+b+"_h"+c+"_d"+f)}};
V.prototype.jb=function(){if(!!this.$){this.Qa();this.Ga("ok_collapse_w"+this.A+"_h"+this.z)}};V.prototype.Qa=function(){this.e.style.width=this.A+"px";this.e.style.height=this.z+"px";this.e.style.left="0";this.e.style.top="0";this.e.style.zIndex=h;this.e.parentNode.style.zIndex=h;this.e.parentNode.parentNode.style.zIndex=h;this.$=g};
V.prototype.bb=function(a,b,c){this.e.style.position="absolute";this.e.style.width=a+"px";this.e.style.height=b+"px";this.e.style.zIndex=9999;this.e.parentNode.style.zIndex=9999;this.e.parentNode.parentNode.style.zIndex=9999;if(a>this.A&&(c==0||c==3))this.e.style.left="-"+(a-this.A)+"px";if(b>this.z&&(c==1||c==0))this.e.style.top="-"+(b-this.z)+"px";this.$=m};
V.prototype.$a=function(a,b){var c=yb(this.e),d=lb(window),e=a-this.A,f=b-this.z,j=c.y,i=f>j,l=d.height-(c.y+this.z),k=i||l>=j,o=c.x,p=e>o,q=d.width-(c.x+this.A),K=p||q>=o,N=0;if(k&&K)N=2;else if(k&&!K)N=3;else if(!k&&K)N=1;else if(!k&&!K)N=0;return N};
var Jc=function(){},Mc=function(a,b,c,d,e){if(!a||!b||c<=0||d<=0)return h;var f=Lb(10);b=Kc(b,c,d,f);var j=Lc(a,b,c,d,e);return new V(j,f)},Kc=function(a,b,c,d){var e=ib().wa();return a+(a.indexOf("?")==-1?"?":"&")+"w="+b+"&h="+c+"&xpc="+d+"&p="+escape(e.location.protocol+"//"+e.location.host)},Lc=function(a,b,c,d,e){var f="border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px",j='<ins style="display:inline-table;'+f+'"><ins style="display:block;'+f+'"><iframe allowtransparency=true frameborder=0 height='+
d+" hspace=0 id="+a+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe></ins></ins>",i=ib(),l=i.ya(e);if(l)l.innerHTML=j;else i.wa().write(j);return i.ya(a)};ya("ExpandableAdSlot",V);ya("ExpandableAdSlotFactory",Jc);var W="";function Nc(a){if(a){if(W!="")W+=",";W+=a}}var Oc=g,Pc=ha("false",g);function Qc(a){return a!=h?'"'+a+'"':'""'}function fa(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ea(a),d=b[a];X(c,d)}function Z(a,b){b!=h&&X(a,fa(b))}function $(a){var b=window,c=ea(a),d=b[a];Z(c,d)}
function Rc(a,b){var c=window,d=ea(a),e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}function Sc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Tc(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==h)a._GA_googleCookieHelper=new n;if(!a._google_cookie_fetched){a._google_cookie_fetched=m;a._GA_googleCookieHelper.cb(Uc(a.google_ad_client))}}}function Uc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Vc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function Wc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Xc(){var a=w&&y("6")&&!y("8"),b=Sa&&y("1.8.1"),c=x&&y("525");if(Za&&(a||b||c))return m;else if(Ya&&(c||b))return m;else if($a&&b)return m;return g}function Yc(a,b){var c=a.google_allow_expandable_ads;if(c!=h&&c==g||!b.body||a.google_ad_output!="html"||Zc(a,b)||$c(a)||ad(a.google_ad_format)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Xc())return g;return m}
function bd(){var a=Math.random(),b=ga("0.2",0.03),c=2*b;if(a<b)return"30143019";if(a<c)return"30143020";return""}function cd(){var a=Math.random(),b=ga("0",0.03),c=2*b;if(a<b)return"30143021";if(a<c)return"30143022";return""}function dd(){var a=Math.random(),b=ga("0.03",0.01),c=2*b;if(a<b)return"6083029";if(a<c)return"6083028";return""}function ed(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}
function fd(a,b,c,d){var e=Wc(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Qc(gd(c))+"></"+f+">");else if(a.google_ad_output=="html")if(hd(a)){var j=a.google_container_id||d||h;a["google_expandable_ad_slot"+e]=Mc("google_ads_frame"+e,gd(c),a.google_ad_width,a.google_ad_height,j)}else{var i='<iframe name="google_ads_frame" width='+
Qc(a.google_ad_width)+" height="+Qc(a.google_ad_height)+" frameborder="+Qc(a.google_ad_frameborder)+" src="+Qc(gd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';i=id(a.google_ad_width,a.google_ad_height,i);a.google_container_id?jd(a.google_container_id,b,i):b.write(i)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+Qc(gd(c))+"></"+f+">")}
function hd(a){if(!Oc)return g;var b=W.indexOf("30143020")!=-1,c=W.indexOf("30143019")!=-1,d=a.google_expandable_iframe;return Pc&&!c||b||d}function kd(a){var b=ha("false",g);return b&&a.indexOf("30143021")==-1||a.indexOf("30143022")!=-1}
function id(a,b,c){var d=kd(W);if(Oc&&d){var e="border:none;height:"+b+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";return'<ins style="display:inline-table;'+e+'"><ins style="display:block;'+e+'">'+c+"</ins></ins>"}return c}function ld(a){for(var b in ba)a[b]=h;for(var b in ca)b=="google_correlator"||(a[b]=h);for(var b in da)a[b]=h;a.google_allow_expandable_ads=h;a.google_container_id=h;a.google_expandable_iframe=h;a.google_tag_js_version=h}
function $c(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function ad(a){return a&&a.indexOf("_sdo")!=-1}
function md(a){var b=h,c=window,d=document,e=aa,f=c.google_ad_format,j=nd(c),i;if(c.google_cpa_choice!=b){c.google_ad_url=j+"/cpa/ads?";i=escape(Uc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(ad(f)){c.google_ad_url=j+"/pagead/sdo?";i=escape(Vc(c.google_ad_client))}else{c.google_ad_url=j+"/pagead/ads?";i=escape(Uc(c.google_ad_client))}c.google_ad_url+=
"client="+i;Y("google_ad_host");Y("google_ad_host_tier_id");var l=c.google_num_slots_by_client,k=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(ad(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if($c(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var K=c.google_ad_client;if(l[K])l[K]+=1;else{l[K]=1;l.length+=1}if(o[q])if(!ad(f)){Z("prev_fmts",o[q].toLowerCase());l.length>1&&X("slot",l[K])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());ad(f)||(o[q]=o[q]?o[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var N="",$b=c.google_ad_channel.split(od),db=0;for(;db<$b.length;db++){var eb=$b[db];if(k[eb])N+=eb+"+";else k[eb]=1}Z("pv_ch",N)}if(c.google_ad_host_channel){$("google_ad_host_channel");var wd=
pd(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",wd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.hb());$("google_page_url");Rc("google_color_bg",e);Rc("google_color_text",e);Rc("google_color_link",e);Rc("google_color_url",e);Rc("google_color_border",e);Rc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");if(Oc=Yc(c,d))if(c.google_expandable_iframe===g)ed(c);else if(i in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=m;else{if(!(c.google_expandable_iframe==m)){var oa=bd();Nc(oa);if(oa=="30143019"||oa==""&&!Pc)ed(c);if(!oa){oa=cd();Nc(oa)}}}else ed(c);
X("eid",W);var ac=c.google_allow_expandable_ads;if(ac!=h)ac?X("ea","1"):X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");
$("google_ui_version");$("google_tag_js_version");$("google_only_ads_with_video");$("google_only_pyv_ads");$("google_disable_video_autoplay");if(a){Z("ff",zb(a));var fb=xb(a),gb=lb();if(fb&&gb){Z("biw",gb.width);Z("bih",gb.height);Z("adx",fb.x);Z("ady",fb.y)}}Bb();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Sc(c);return m}
function pd(a,b){var c=a.split("|"),d=-1,e=[],f=0;for(;f<c.length;f++){var j=c[f].split(od);b[f]||(b[f]={});var i="",l=0;for(;l<j.length;l++){var k=j[l];if(!(k==""))if(b[f][k])i+="+"+k;else b[f][k]=1}i=i.slice(1);e[f]=i;if(i!="")d=f}var o="";if(d>-1){var f=0;for(;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function qd(){var a=window,b=document;Tc(a);var c=dd();Nc(c);var d;if(c=="6083029"){var e="google_temp_span";d=a.google_container_id&&kb(a.google_container_id)||kb(e);if(!d&&!a.google_container_id){b.write("<span id="+e+"></span>");d=kb(e)}}var f=md(d);d&&d.id==e&&nb(d);if(!!f){fd(a,b,a.google_ad_url);ld(a)}}function gd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function rd(){qd();return m}
function Zc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return m}
function sd(a){var b=window,c=h,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(ad(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;td(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ia();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function ud(a){if(a in vd)return vd[a];return vd[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var vd={};function ja(){return ud("msie")&&!window.opera}
function xd(a){var b={},c=a.split("?"),d=c[c.length-1].split("&"),e=0;for(;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(j){}}return b}function yd(){var a=window,b=xd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function zd(a,b){for(var c in b)a["google_"+c]=b[c]}
function Ad(a,b){if(!b)return a.location;return a.referrer}function Bd(a,b){if(!b&&a.google_referrer_url==h)return"0";else if(b&&a.google_referrer_url==h)return"1";else if(!b&&a.google_referrer_url!=h)return"2";else if(b&&a.google_referrer_url!=h)return"3";return"4"}function Cd(a,b,c,d){a.page_url=Ad(c,d);a.page_location=h}function Dd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=Ad(c,d)||"EMPTY"}
function Ed(a,b){var c={},d=Zc(a,b);c.iframing=Bd(a,d);!!a.google_page_url?Dd(c,a,b,d):Cd(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:h;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Fd(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=h;b.page_url=c;b.page_location=a.location;b.last_modified_time=h;b.referrer_url=c;return b}
function td(a,b){var c;c=a.google_page_url==h&&Gd[b.domain]?Fd(b):Ed(a,b);zd(a,c)}function jd(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Gd={};Gd["ad.yieldmanager.com"]=m;var od=/[+, ]/;window.google_render_ad=qd;var Hd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Id(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Hd;if(e.length>=2)f=f||e[e.length-2]in Hd;return f}
function Jd(a,b,c){if(Id(a)){a.google_new_domain_checked=1;return g}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return m}}return g}function nd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Id(a)&&a.google_new_domain_enabled==1)return b;return c};function Kd(a,b){var c="script",d=Jd(a,b,ga("1",0.01));d&&ja()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}yd();sd(rd);Kd(window,document);
})()
